name: Publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci
        working-directory: packages/api

      - name: Update version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(npm version patch -m "Update version to %s")
          echo "Updated version from $CURRENT_VERSION to $NEW_VERSION"
        working-directory: packages/api

      - name: Commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add package.json package-lock.json
          git commit -m "Update version to $(node -p "require('./package.json').version")"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        working-directory: packages/api

      - name: Build project
        run: npm run build
        working-directory: packages/api

      - name: Publish to npm
        run: npm run deploy
        working-directory: packages/api
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
